apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nnoe-agent
  namespace: nnoe
  labels:
    app: nnoe-agent
spec:
  selector:
    matchLabels:
      app: nnoe-agent
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    scheme: http

