apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nnoe

resources:
  - management/namespace.yaml
  - management/etcd-statefulset.yaml
  - agent/daemonset.yaml
  - agent/configmap.yaml

commonLabels:
  app: nnoe
  version: v0.1.0

images:
  - name: ghcr.io/nnoe/agent
    newTag: latest

